title: 也无风雨也无晴
subtitle: 回首向来萧瑟处
author: 未署名

github_username: wenzhao-wu
url: "https://wenzhao-wu.github.io"
timezone: Asia/Shanghai

markdown: kramdown
kramdown:
  input: GFM

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
